name: Build and Publish

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      publish_to_npm:
        description: 'Publish to npm'
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build package
        run: yarn build:package

      - name: Run tests
        run: yarn test || echo "No tests specified"
        
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: package-dist
          path: dist/
          retention-days: 1

  publish-npm:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v') || github.event.inputs.publish_to_npm == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Download package artifact
        uses: actions/download-artifact@v4
        with:
          name: package-dist
          path: dist/
          
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: |
            *.tgz

  deploy-demo:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      # Build demo app
      - name: Build demo app
        run: yarn build:demo

      # Deploy demo to GitHub Pages
      - name: Deploy demo to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: demo-dist
          branch: gh-pages
